// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/autoscaler.proto

package project

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TheAutocaler_CheckResourcesUsage_FullMethodName = "/theautoscaler.TheAutocaler/CheckResourcesUsage"
)

// TheAutocalerClient is the client API for TheAutocaler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type TheAutocalerClient interface {
	// Sends a greeting
	CheckResourcesUsage(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckReply, error)
}

type theAutocalerClient struct {
	cc grpc.ClientConnInterface
}

func NewTheAutocalerClient(cc grpc.ClientConnInterface) TheAutocalerClient {
	return &theAutocalerClient{cc}
}

func (c *theAutocalerClient) CheckResourcesUsage(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckReply)
	err := c.cc.Invoke(ctx, TheAutocaler_CheckResourcesUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TheAutocalerServer is the server API for TheAutocaler service.
// All implementations must embed UnimplementedTheAutocalerServer
// for forward compatibility.
//
// The greeting service definition.
type TheAutocalerServer interface {
	// Sends a greeting
	CheckResourcesUsage(context.Context, *CheckRequest) (*CheckReply, error)
	mustEmbedUnimplementedTheAutocalerServer()
}

// UnimplementedTheAutocalerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTheAutocalerServer struct{}

func (UnimplementedTheAutocalerServer) CheckResourcesUsage(context.Context, *CheckRequest) (*CheckReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckResourcesUsage not implemented")
}
func (UnimplementedTheAutocalerServer) mustEmbedUnimplementedTheAutocalerServer() {}
func (UnimplementedTheAutocalerServer) testEmbeddedByValue()                      {}

// UnsafeTheAutocalerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TheAutocalerServer will
// result in compilation errors.
type UnsafeTheAutocalerServer interface {
	mustEmbedUnimplementedTheAutocalerServer()
}

func RegisterTheAutocalerServer(s grpc.ServiceRegistrar, srv TheAutocalerServer) {
	// If the following call pancis, it indicates UnimplementedTheAutocalerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TheAutocaler_ServiceDesc, srv)
}

func _TheAutocaler_CheckResourcesUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheAutocalerServer).CheckResourcesUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TheAutocaler_CheckResourcesUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheAutocalerServer).CheckResourcesUsage(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TheAutocaler_ServiceDesc is the grpc.ServiceDesc for TheAutocaler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TheAutocaler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "theautoscaler.TheAutocaler",
	HandlerType: (*TheAutocalerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckResourcesUsage",
			Handler:    _TheAutocaler_CheckResourcesUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/autoscaler.proto",
}
