// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/autoscaler.proto

package project

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the container ID.
type CheckReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReply) Reset() {
	*x = CheckReply{}
	mi := &file_proto_autoscaler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReply) ProtoMessage() {}

func (x *CheckReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_autoscaler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReply.ProtoReflect.Descriptor instead.
func (*CheckReply) Descriptor() ([]byte, []int) {
	return file_proto_autoscaler_proto_rawDescGZIP(), []int{0}
}

// The response message containing the greetings
type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpuPercent,proto3" json:"cpuPercent,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,2,opt,name=memoryPercent,proto3" json:"memoryPercent,omitempty"`
	ContainerId   string                 `protobuf:"bytes,3,opt,name=containerId,proto3" json:"containerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_proto_autoscaler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_autoscaler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_autoscaler_proto_rawDescGZIP(), []int{1}
}

func (x *CheckRequest) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *CheckRequest) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *CheckRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

var File_proto_autoscaler_proto protoreflect.FileDescriptor

const file_proto_autoscaler_proto_rawDesc = "" +
	"\n" +
	"\x16proto/autoscaler.proto\x12\rtheautoscaler\"\f\n" +
	"\n" +
	"CheckReply\"v\n" +
	"\fCheckRequest\x12\x1e\n" +
	"\n" +
	"cpuPercent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12$\n" +
	"\rmemoryPercent\x18\x02 \x01(\x01R\rmemoryPercent\x12 \n" +
	"\vcontainerId\x18\x03 \x01(\tR\vcontainerId2_\n" +
	"\fTheAutocaler\x12O\n" +
	"\x13CheckResourcesUsage\x12\x1b.theautoscaler.CheckRequest\x1a\x19.theautoscaler.CheckReply\"\x00BF\n" +
	"\x16io.grpc.the-autoscalerB\x12TheAutoscalerProtoP\x01Z\x16the-autoscaler/projectb\x06proto3"

var (
	file_proto_autoscaler_proto_rawDescOnce sync.Once
	file_proto_autoscaler_proto_rawDescData []byte
)

func file_proto_autoscaler_proto_rawDescGZIP() []byte {
	file_proto_autoscaler_proto_rawDescOnce.Do(func() {
		file_proto_autoscaler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_autoscaler_proto_rawDesc), len(file_proto_autoscaler_proto_rawDesc)))
	})
	return file_proto_autoscaler_proto_rawDescData
}

var file_proto_autoscaler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_autoscaler_proto_goTypes = []any{
	(*CheckReply)(nil),   // 0: theautoscaler.CheckReply
	(*CheckRequest)(nil), // 1: theautoscaler.CheckRequest
}
var file_proto_autoscaler_proto_depIdxs = []int32{
	1, // 0: theautoscaler.TheAutocaler.CheckResourcesUsage:input_type -> theautoscaler.CheckRequest
	0, // 1: theautoscaler.TheAutocaler.CheckResourcesUsage:output_type -> theautoscaler.CheckReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_autoscaler_proto_init() }
func file_proto_autoscaler_proto_init() {
	if File_proto_autoscaler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_autoscaler_proto_rawDesc), len(file_proto_autoscaler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_autoscaler_proto_goTypes,
		DependencyIndexes: file_proto_autoscaler_proto_depIdxs,
		MessageInfos:      file_proto_autoscaler_proto_msgTypes,
	}.Build()
	File_proto_autoscaler_proto = out.File
	file_proto_autoscaler_proto_goTypes = nil
	file_proto_autoscaler_proto_depIdxs = nil
}
